force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Client_Number__c.field-meta.xml
<CustomField>
    <fullName>Client_Number__c</fullName>
    <externalId>true</externalId>
    <label>Client Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Legal_Advisor__c.field-meta.xml
<CustomField>
    <fullName>Legal_Advisor__c</fullName>
    <label>Legal Advisor</label>
    <referenceTo>Legal_Advisor__c</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Legal_Advisor</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Legal_Advisor__c/Legal_Advisor__c.object-meta.xml
<CustomObject>
    <label>Legal Advisor</label>
    <nameField>
        <label>Legal Advisor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Advisors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Legal_Advisor__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>70</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Legal_Advisor__c/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <defaultValue>&apos;Disabled&apos;</defaultValue>
    <label>Account Status</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ucl_ClientController/ucl_ClientControllerTest.cls
@isTest
public class ucl_ClientControllerTest
{
    @isTest static void testGetClientCountByAdvisor()
    {
        Legal_Advisor__c legalAdvisor = new Legal_Advisor__c(
            Account_Number__c = 'a209ebbb-39c6-4852-8732-82237c0674fb',
            Account_Name__c = 'Fadeo',
            Account_Status__c = 'Enabled'
        );
        
        insert legalAdvisor;

        Client__c client = new Client__c(
            Legal_Advisor__c = legalAdvisor.Id,
            First_Name__c = 'Fran',
            Last_Name__c = 'Ruddick',
            Email__c = 'fruddick0@issuu.com',
            Phone__c = '390-285-2477',
            Address__c = '434 Maple Drive',
            Client_Number__c = '12afa152-8115-492b-bb49-87399ab49af8',
            CreatedByUser__c = false
        );
        
        insert client;

        Test.startTest();
        Integer clientCount = ucl_ClientController.getClientCountByAdvisor(legalAdvisor.Id);
        Test.stopTest();

        System.assertEquals(1, clientCount, 'The number of Client__c records should be 1');
    }
}