force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Client_Number__c.field-meta.xml
<CustomField>
    <fullName>Client_Number__c</fullName>
    <externalId>true</externalId>
    <label>Client Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Legal_Advisor__c.field-meta.xml
<CustomField>
    <fullName>Legal_Advisor__c</fullName>
    <label>Legal Advisor</label>
    <referenceTo>Legal_Advisor__c</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Legal_Advisor</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Legal_Advisor__c/Legal_Advisor__c.object-meta.xml
<CustomObject>
    <label>Legal Advisor</label>
    <nameField>
        <label>Legal Advisor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Advisors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Legal_Advisor__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>70</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ucl_AdminService/ucl_AdminService.cls
public with sharing class ucl_AdminService
{
    private static Map<String, String> getUniqueClientIdsFromJson(String jsonData)
    {
        Map<String, String> uniqueClientIds = new Map<String, String>();
        
        List<ucl_LegalAdvisor> legalAdvisors = ucl_DataParser.parseLegalAdvisorsFromJson(jsonData);
        for (ucl_LegalAdvisor legalAdvisor : legalAdvisors)
        {
            List<ucl_Client> clients = legalAdvisor.Clients;
            if (clients != null && !clients.isEmpty())
            {
                for (ucl_Client client : clients)
                {
                    uniqueClientIds.put(legalAdvisor.AccountNumber, client.ClientNumber);
                }
            }
        }

        return uniqueClientIds;
    }

    public static void deleteClientsNotInJson(String jsonData)
    {
        Map<String, String> parsedClientIds = getUniqueClientIdsFromJson(jsonData);
    
        List<Legal_Advisor__c> legalAdvisors = 
        [
            SELECT Id, Account_Number__c 
            FROM Legal_Advisor__c 
            WHERE Account_Number__c IN :parsedClientIds.keySet()
        ];
    
        Map<Id, Legal_Advisor__c> legalAdvisorMap = new Map<Id, Legal_Advisor__c>(legalAdvisors);
    
        List<Client__c> allClients = 
        [
            SELECT Id, Legal_Advisor__c, Client_Number__c
            FROM Client__c 
            WHERE CreatedByUser__c = false
            AND Legal_Advisor__c IN :legalAdvisorMap.keySet()];
    
        List<Client__c> clientsToDelete = new List<Client__c>();
    
        for (Client__c client : allClients)
        {
            Legal_Advisor__c legalAdvisor = legalAdvisorMap.get(client.Legal_Advisor__c);
            if (client.Client_Number__c != parsedClientIds.get(String.valueOf(legalAdvisor.Account_Number__c)))
            {
                clientsToDelete.add(client);
            }
        }
    
        if (!clientsToDelete.isEmpty())
        {
            delete clientsToDelete;
        }
    }
}