force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Client Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/Client_Number__c.field-meta.xml
<CustomField>
    <fullName>Client_Number__c</fullName>
    <externalId>true</externalId>
    <label>Client Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Legal_Advisor__c.field-meta.xml
<CustomField>
    <fullName>Legal_Advisor__c</fullName>
    <label>Legal Advisor</label>
    <referenceTo>Legal_Advisor__c</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Legal_Advisor</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Legal_Advisor__c/Legal_Advisor__c.object-meta.xml
<CustomObject>
    <label>Legal Advisor</label>
    <nameField>
        <label>Legal Advisor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Advisors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Legal_Advisor__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>70</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Legal_Advisor__c/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <defaultValue>&apos;Disabled&apos;</defaultValue>
    <label>Account Status</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ucl_LegalAdvisorService/ucl_LegalAdvisorServiceTest.cls
@isTest
public class ucl_LegalAdvisorServiceTest
{
    @isTest static void testLegalAdvisorsProcess()
    {
        // Arrange

        Legal_Advisor__c testLegalAdvisor = new Legal_Advisor__c
        (
            Account_Number__c = 'TestAccountNumber',
            Account_Name__c = 'TestAccountName',
            Name = 'TestAccountName',
            Account_Status__c = 'Enabled',
            As_Of_Date__c = Date.today()
        );
        
        insert testLegalAdvisor;

        ucl_Client testClient = new ucl_Client();
        testClient.FirstName = 'TestFirstName';
        testClient.LastName = 'TestLastName';
        testClient.Email = 'test@example.com';
        testClient.Phone = '1234567890';
        testClient.Address = 'Test Address';
        testClient.ClientNumber = 'TestClientNumber';

        ucl_LegalAdvisor testLegalAdvisorModel = new ucl_LegalAdvisor();
        testLegalAdvisorModel.AccountNumber = 'TestAccountNumber';
        testLegalAdvisorModel.AccountName = 'TestAccountName';
        testLegalAdvisorModel.AccountStatus = 'Enabled';
        testLegalAdvisorModel.AsOfDate = String.valueOf(Date.today().month()) + '/' + String.valueOf(Date.today().day()) + '/' + String.valueOf(Date.today().year());
        testLegalAdvisorModel.Clients = new List<ucl_Client>{testClient};

        // Act    
        
        Test.startTest();
        ucl_LegalAdvisorService.processLegalAdvisors(new List<ucl_LegalAdvisor>{testLegalAdvisorModel});
        Test.stopTest();

        // Assert
        
        Legal_Advisor__c actualLegalAdvisor = [SELECT Id, Account_Number__c, Account_Name__c, Account_Status__c, As_Of_Date__c FROM Legal_Advisor__c WHERE Id = :testLegalAdvisor.Id];
        System.assertEquals(testLegalAdvisorModel.AccountNumber, actualLegalAdvisor.Account_Number__c);
        System.assertEquals(testLegalAdvisorModel.AccountName, actualLegalAdvisor.Account_Name__c);
        System.assertEquals(testLegalAdvisorModel.AccountStatus, actualLegalAdvisor.Account_Status__c);
        System.assertEquals(testLegalAdvisorModel.AsOfDate, String.valueOf(actualLegalAdvisor.As_Of_Date__c.month()) + '/' + String.valueOf(actualLegalAdvisor.As_Of_Date__c.day()) + '/' + String.valueOf(actualLegalAdvisor.As_Of_Date__c.year()));

        List<Client__c> actualClients = [SELECT Id, First_Name__c, Last_Name__c, Email__c, Phone__c, Address__c, Client_Number__c, Legal_Advisor__c FROM Client__c WHERE Legal_Advisor__c = :testLegalAdvisor.Id];
        System.assertEquals(1, actualClients.size());
        System.assertEquals(testClient.FirstName, actualClients[0].First_Name__c);
        System.assertEquals(testClient.LastName, actualClients[0].Last_Name__c);
        System.assertEquals(testClient.Email, actualClients[0].Email__c);
        System.assertEquals(testClient.Phone, actualClients[0].Phone__c);
        System.assertEquals(testClient.Address, actualClients[0].Address__c);
        System.assertEquals(testClient.ClientNumber, actualClients[0].Client_Number__c);
    }


@isTest static void testProcessLegalAdvisorsWithExistingEnabledLegalAdvisor() {
    // Prepare test data
    Legal_Advisor__c existingLegalAdvisor = new Legal_Advisor__c(
        Account_Number__c = 'TestAccountNumber',
        Account_Name__c = 'TestAccountName',
        Name = 'TestAccountName',
        Account_Status__c = 'Enabled',
        As_Of_Date__c = Date.today()
    );
    insert existingLegalAdvisor;

    ucl_Client testClient = new ucl_Client();
    testClient.FirstName = 'TestFirstName';
    testClient.LastName = 'TestLastName';
    testClient.Email = 'test@example.com';
    testClient.Phone = '1234567890';
    testClient.Address = 'Test Address';
    testClient.ClientNumber = 'TestClientNumber';

    ucl_LegalAdvisor testLegalAdvisorModel = new ucl_LegalAdvisor();
    testLegalAdvisorModel.AccountNumber = 'TestAccountNumber';
    testLegalAdvisorModel.AccountName = 'TestAccountName';
    testLegalAdvisorModel.AccountStatus = 'Disabled';
    testLegalAdvisorModel.AsOfDate = String.valueOf(Date.today().month()) + '/' + String.valueOf(Date.today().day()) + '/' + String.valueOf(Date.today().year());
    testLegalAdvisorModel.Clients = new List<ucl_Client>{testClient};

    Test.startTest();
    // Call the method to test
    ucl_LegalAdvisorService.processLegalAdvisors(new List<ucl_LegalAdvisor>{testLegalAdvisorModel});
    Test.stopTest();

    List<Client__c> actualClients = [SELECT Id, First_Name__c, Last_Name__c, Email__c, Phone__c, Address__c, Client_Number__c, Legal_Advisor__c FROM Client__c WHERE Legal_Advisor__c = :existingLegalAdvisor.Id];
    System.assertEquals(1, actualClients.size());
    System.assertEquals(testClient.FirstName, actualClients[0].First_Name__c);
    System.assertEquals(testClient.LastName, actualClients[0].Last_Name__c);
}}