force-app/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <label>ErrorLog</label>
    <nameField>
        <label>ErrorLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ErrorLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ErrorLog__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <label>ErrorMessage</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ucl_ErrorLogController/ucl_ErrorLogController.cls
public with sharing class ucl_ErrorLogController
{
    @AuraEnabled(cacheable=true)
    public static List<ErrorLog__c> getErrorLogs()
    {
        return [SELECT Id, Name, ErrorMessage__c FROM ErrorLog__c];
    }

    @future(callout=true)
    public static void deleteErrorLogs(Integer deadlineDays)
    {
        Date limitCreatedDate = Date.today().addDays(-deadlineDays);

        List<ErrorLog__c> errorLogs = 
        [
            SELECT Id 
            FROM ErrorLog__c 
            WHERE CreatedDate < :limitCreatedDate
        ];

        delete errorLogs;
    }
}