force-app/main/default/objects/ErrorLog__c/ErrorLog__c.object-meta.xml
<CustomObject>
    <label>ErrorLog</label>
    <nameField>
        <label>ErrorLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ErrorLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ErrorLog__c/fields/CreatedByUser__c.field-meta.xml
<CustomField>
    <fullName>CreatedByUser__c</fullName>
    <defaultValue>true</defaultValue>
    <label>CreatedByUser</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ErrorLog__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <label>ErrorMessage</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ucl_ErrorLogController/ucl_ErrorLogControllerTest.cls
@isTest
private class ucl_ErrorLogControllerTest
{
    @isTest static void testGetErrorLogs()
    {
        //Arrange
        ErrorLog__c log = new ErrorLog__c(CreatedByUser__c = false, ErrorMessage__c='Test Error');
        insert log;

        //Act
        Test.startTest();
        List<ErrorLog__c> logs = ucl_ErrorLogController.getErrorLogs();
        Test.stopTest();

        //Assert
        ErrorLog__c log = logs[0];
        System.assertEquals(1, logs.size());
        System.assertEquals('Test Error', log.ErrorMessage__c);
    }

    @isTest static void testErrorLogsShouldNotBeDeleted()
    { 
        //Arrange
        ErrorLog__c log = new ErrorLog__c(CreatedByUser__c = false, ErrorMessage__c='Test Error');
        insert log;
        Integer completedDays = 2;

        //Act
        Test.startTest();
        ucl_ErrorLogController.deleteErrorLogs(completedDays); 
        Test.stopTest();

        //Assert
        List<ErrorLog__c> logs = 
        [
            SELECT Id 
            FROM ErrorLog__c 
            WHERE Id = :log.Id
        
        ];
        System.assert.IsTrue(logs.size() == 1);
    }

    @isTest static void testErrorLogsShouldBeDeleted()
    {
        //Arrange
        ErrorLog__c log = new ErrorLog__c(CreatedByUser__c = false, ErrorMessage__c='Test Error');
        insert log;
        Integer completedDays = 31;

        //Act
        Test.startTest();
        ucl_ErrorLogController.deleteErrorLogs(completedDays); 
        Test.stopTest();

        //Assert
        List<ErrorLog__c> logs = 
        [
            SELECT Id 
            FROM ErrorLog__c 
            WHERE Id = :log.Id
        
        ];
        System.assert.IsTrue(logs.size() == 0);
    }
}